[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001

lib_deps =
    bodmer/TFT_eSPI
    adafruit/Adafruit TCS34725
    adafruit/Adafruit PWM Servo Driver Library
    adafruit/RTClib
    paulstoffregen/XPT2046_Touchscreen
    adafruit/Adafruit BusIO

build_flags =
    -DUSER_SETUP_LOADED
    -DILI9341_DRIVER
    -DTFT_MOSI=23
    -DTFT_MISO=19
    -DTFT_SCLK=18
    -DTFT_CS=15
    -DTFT_DC=27
    -DTFT_RST=4
    -DTOUCH_CS=33
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_FONT8
    -DLOAD_GFXFF
    -DSMOOTH_FONT
